"""First revision

Revision ID: 1e313b3b983e
Revises: 
Create Date: 2025-11-26 15:41:10.305778

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '1e313b3b983e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
